### ISSUE TITLE
Multi-line f-strings can help improving the readability of the SQL statements

### ISSUE THREAD

**Issue by airnandez** [in2p3-dp0/qserv-tests#1]
You may want to consider using Python multi-line f-strings for separating and improving the readability of the SQL statements, in particular when they are complex.

For instance, [this query](https://github.com/in2p3-dp0/qserv-tests/blob/a86f17224014ac4a2b5f752b052491de31067be7/python/test_dr6-wfd.py#L62) could be written as:

```python
query = f"""
  SELECT
      dref.coord_ra as ra,
      dref.coord_dec as dec,
      dref.ext_shapeHSM_HsmShapeRegauss_e1,
      dref.ext_shapeHSM_HsmShapeRegauss_e2,
      dref.objectId as id, 
      dfrc.i_modelfit_CModel_instFlux

   FROM
      -- indicate which tables will be used and at the same time we define a short alias for each table
      dc2_object_run2_2i_dr6_wfd.dpdd_ref as dref,
      dc2_object_run2_2i_dr6_wfd.position as dpos,
      dc2_object_run2_2i_dr6_wfd.dpdd_forced as dfrc

   WHERE
      -- specify the ra, dec bounding box and we use the special SQL function: scisql_s2PtInBox
      -- It is mandatory to put this constraint right after the WHERE statement
      -- Using the special function is mandatory to use the special qserv optimization mechanism
      scisql_s2PtInBox(coord_ra, coord_dec, {ra_min}, {dec_min}, {ra_max}, {dec_max}) = 1

      -- join between the 3 tables on the objectId. It gurantees that each line extracted from the 3 tables
      -- corresponds to the same object
      AND dref.objectId = dpos.objectId
      AND dfrc.objectId = dpos.objectId

      -- add all the other selection cuts
      AND dpos.detect_isPrimary = 1
      AND dfrc.i_modelfit_CModel_flag = 0
      AND dfrc.i_modelfit_CModel_instFlux > 0
      AND dref.base_SdssCentroid_flag = 0

      -- we can have SQL math funcions in the query
      AND dref.base_Blendedness_abs < POWER(10, -0.375)
      AND dref.base_Blendedness_abs_instFlux IS NULL 
      AND dref.base_ClassificationExtendedness_flag = 0
      AND dref. base_ClassificationExtendedness_value > 0 
      AND ext_shapeHSM_HsmShapeRegauss_flag = 0

      -- crazy cut on the flux S/N for demonstration purpose to limit the number of returned lines.
      -- A more reasonable cut would be ~30 as in the commented line
      AND dfrc.i_modelfit_CModel_flag = 0
      AND dfrc.i_modelfit_CModel_instFlux > 0
      AND dfrc.i_modelfit_CModel_instFlux/dfrc.i_modelfit_CModel_instFluxErr > 1000 
      AND dref.ext_shapeHSM_HsmShapeRegauss_resolution >= 0.3
      AND dref.ext_shapeHSM_HsmShapeRegauss_sigma <= 0.4

      -- another example of SQL math
      AND SQRT(POWER(dref.ext_shapeHSM_HsmShapeRegauss_e1, 2)+POWER(dref.ext_shapeHSM_HsmShapeRegauss_e2, 2)) < 2
"""
query += query_clean + ";"
```

The same technique can be used for other SQL statements (e.g. [here](https://github.com/in2p3-dp0/qserv-tests/blob/a86f17224014ac4a2b5f752b052491de31067be7/python/test_dr6-wfd.py#L51)) and in other `*.py` files.

**Comment by boutigny** [comment]
I will implement this but unfortunately it seems that pd.read_sql_query() doesn't accept the comment lines

**Comment by airnandez** [comment]
According to this [StackOverflow question](https://stackoverflow.com/questions/35138740/is-there-a-way-to-write-a-pandas-sql-query-across-multiple-lines-with-comments), the interpretation of the SQL comments depends on the system processing the query.

The [MariaDB documentation](https://mariadb.com/kb/en/comment-syntax/) states that comments can indeed start by `--`. You may want to try with block multi-line comments (i.e. `/* blah blah blah */`) to see if that works.

An alternative would be to pre-process the query to remove the lines starting by `--` (via a regular expression) before passing the query to pandas.

I find your comments to the SQL statements are useful information to keep.

**Comment by boutigny** [comment]
I also tried the /*  */  but it doesn't work either. I was also thinking of a pre-process step before submitting the query

**Comment by boutigny** [comment]
Done. I am now using the python package `sqlparse` to format queries and filter comment out

**Comment by airnandez** [comment]
Thanks @boutigny. I'm closing this issue.
